apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: k8s-nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /
    server: NFS_IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: k8s-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: nfs
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: k8s-nfs
spec:
  containers:
    - name: nfs-client
      image: alpine:3.14
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - 'while true; do echo "I am working..."; date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
      securityContext:
        privileged: true
      volumeMounts:
      - name: nfs
        mountPath: "/mnt"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-claim
      readOnly: false
