# Create a service to expose the NFS server
# to pods inside the cluster.
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: k8s-nfs
spec:
  selector:
    role: nfs-server
  ports:
    - name: nfs
      port: 2049
---
# Run the NFS server image in a pod that is
# exposed by the service.
kind: Pod
apiVersion: v1
metadata:
  name: nfs-server
  namespace: k8s-nfs
  labels:
    role: nfs-server
spec:
  containers:
    - name: nfs-server
      image: erichough/nfs-server:2.2.1
      securityContext:
        privileged: true
      env:
      - name: NFS_PORT
        value: "2049"
      - name: NFS_VERSION
        value: "4.2"
      - name: NFS_DISABLE_VERSION_3
        value: "1"
      - name: NFS_LOG_LEVEL
        value: DEBUG
      - name: NFS_EXPORT_0
        value: /data *(rw,sync,fsid=0,crossmnt,no_subtree_check,no_root_squash)
      volumeMounts:
        - mountPath: /data
          name: volume
      ports:
        - name: nfs
          containerPort: 2049
  volumes:
    - emptyDir: { }
      name: volume
